### ISSUE TITLE
Add a community part to flexiblepower.org and cleanup download section

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#12]
Flexiblepower.org need to point to github and the powermatcher website.
- [ ] Cleanup download section
- [ ] Translate all dutch text
- [ ]  Add a community section

**Comment by Sander3003** [comment]
We also need to cleanup the download section of flexiblepower.org

**Comment by Sander3003** [comment]
@victor481 Can you write a text for the community part?

**Comment by Sander3003** [comment]
Will be ready on 15th October. Please paste the result here!

**Comment by victor481** [comment]
The website you are currently visiting is the website of the Flexible-power Alliance Network (FAN). The FAN is a non-profit organization which exists in order to help develop and distribute the PowerMatcher Suite. The actual product website for the PowerMatcher Suite is located at http://www.powermatcher.org/. 

PowerMatcher Suite is an innovative software solution for exchanging electricity between end-users, local generation and “prosumers”. You can use the technology for your own distributed energy implementation for free, by downloading the software from http://www.powermatcher.org/. From applications on domestic scale to the balancing of electricity on large scale grids with thousands of distributed energy resources and loads: PowerMatcher Suite is the smart-grid technology for you. 

FAN strongly beliefs in the power of the open-source community, which is why PowerMatcher Suite is 100% open source and in open development. If you want to contribute to PowerMatcher Suite, or need to adapt PowerMatcher Suite to satisfy the needs for your PowerMatcher Suite-based application, we redirect you to our product webpage http://www.powermatcher.org/. All the software code is available on https://github.com/flexiblepower/powermatcher including documentation and a set of tutorials. Github enables social coding, easy version control and reporting of issues. The community welcomes new developers and contributions. It is not obligatory to be part of the alliance in order to contribute.

**Comment by alex254** [comment]
- piece too generic
- mention more concrete open source benefits of using fpai & pm; like easy driver development, hobbyists etc

**Comment by Sander3003** [comment]
@wilcowijbrandi please contact Bert den Ouden about this topic

**Comment by alex254** [comment]
@victor481 Victor can you update the text?

**Comment by Sander3003** [comment]
This issue will be addressed by the FAN marketing imitative.
