### ISSUE TITLE
Limited process description needed to get new developers started

### ISSUE THREAD

**Issue by Sander3003** [flexiblepower/FAN-wiki#15]
- [x] On-boarding process
- [x] Code review process
- [x] Test process
- [x] Bug tracking process
- [x] New features process

**Comment by Sander3003** [comment]
This could me a help: http://heff.github.io/contributing/#/32

**Comment by Sander3003** [comment]
https://github.com/flexiblepower/FAN-wiki/wiki/Bug-tracking-process @flexiblepower/powermatcher-developers @flexiblepower/fpai-developers can you review the process and report your findings here?

**Comment by LoekJa** [comment]
- Combine point 1 and 2: Report using following URL's and include as much as possible background on the bug.
- At point 3: what if the bug report is a duplicate?
- At point 4: what happens if a developer cannot reproduce/has to little info/does not understand/disagrees (no bug).
- At point 6: when is a patch accepted? Who makes the descision?

**Comment by Sander3003** [comment]
Thanks for the feedback, I made some changes.
